from __future__ import annotations

import datetime
from pathlib import Path

from atlas_agent.events.log import EventLogger


def generate_reflection(
    memory_dir: Path,
    reports_dir: Path,
    *,
    event_logger: EventLogger | None = None,
    run_id: str | None = None,
    command: str = "atlas agent reflect",
    mode: str = "paper",
) -> Path:
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d-%H%M")
    target_dir = reports_dir / "reflections"
    target_dir.mkdir(parents=True, exist_ok=True)
    
    path = target_dir / f"{timestamp}-reflection.md"
    
    # Placeholder logic
    content = f"""# Self-Reflection Report: {timestamp}

## What Worked
- [Placeholder] Strategy execution followed risk gates.

## What Failed
- [Placeholder] No specific failures detected in latest session.

## Lessons to Remember
- [Placeholder] Stick to daily position size limits.

## Skill Updates
- [Placeholder] Consider improving pre-market research depth.

## Questions for User
- How should I adjust risk tolerance for high-volatility assets?

---
Generated by Atlas Agent
"""
    path.write_text(content, encoding="utf-8")
    if event_logger is not None and run_id is not None:
        event_logger.write(
            "reflection_written",
            run_id=run_id,
            command=command,
            mode=mode,
            payload={"path": str(path)},
        )
    return path
