from __future__ import annotations

import datetime
from pathlib import Path

def generate_reflection(memory_dir: Path, reports_dir: Path) -> Path:
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d-%H%M")
    target_dir = reports_dir / "reflections"
    target_dir.mkdir(parents=True, exist_ok=True)
    
    path = target_dir / f"{timestamp}-reflection.md"
    
    # Placeholder logic
    content = f"""# Self-Reflection Report: {timestamp}

## What Worked
- [Placeholder] Strategy execution followed risk gates.

## What Failed
- [Placeholder] No specific failures detected in latest session.

## Lessons to Remember
- [Placeholder] Stick to daily position size limits.

## Skill Updates
- [Placeholder] Consider improving pre-market research depth.

## Questions for User
- How should I adjust risk tolerance for high-volatility assets?

---
Generated by Atlas Agent
"""
    path.write_text(content, encoding="utf-8")
    return path
