# ==============================================================================
# PROJECT: Atlas Agent
# FILE:    learning/reflections.py
# PURPOSE: Writes the agent's periodic reflection — a dated markdown note on what
#          happened and what it might mean.
# DEPS:    events.log (the reflection is itself an auditable event)
# ==============================================================================

# --- IMPORTS ---
from __future__ import annotations

import datetime
from pathlib import Path

from atlas_agent.events.log import EventLogger


# ==============================================================================
# REFLECTION GENERATION
# ==============================================================================

def generate_reflection(
    memory_dir: Path,
    reports_dir: Path,
    *,
    event_logger: EventLogger | None = None,
    run_id: str | None = None,
    command: str = "atlas agent reflect",
    mode: str = "paper",
) -> Path:
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d-%H%M")
    target_dir = reports_dir / "reflections"
    target_dir.mkdir(parents=True, exist_ok=True)
    
    path = target_dir / f"{timestamp}-reflection.md"
    
    # No automated analysis is implemented behind this command yet. Rather than fill
    # the sections with plausible-looking, invented insights — which read as if they
    # were derived from the session and would be indistinguishable from real ones — we
    # state plainly that nothing was analysed. This is the project's "No fake insights
    # are invented" rule (see reflection/generator.py); a data-grounded reflection is
    # produced by the separate `atlas reflection` subsystem, not here.
    not_assessed = "Not assessed — no automated analysis was performed."
    content = f"""# Self-Reflection Report: {timestamp}

_No automated analysis was performed. This is a static reflection stub: the lines below
are not derived from your trading data, and no insights are invented here._

## What Worked
- {not_assessed}

## What Failed
- {not_assessed}

## Lessons to Remember
- {not_assessed}

## Skill Updates
- {not_assessed}

## Questions for User
- {not_assessed}

---
Generated by Atlas Agent — static stub, no fabricated insights.
"""
    path.write_text(content, encoding="utf-8")
    if event_logger is not None and run_id is not None:
        event_logger.write(
            "reflection_written",
            run_id=run_id,
            command=command,
            mode=mode,
            payload={"path": str(path)},
        )
    return path
