# ==============================================================================
# PROJECT: Atlas Agent
# FILE:    research/errors.py
# PURPOSE: The error types of the research domain, and their sanitised messages.
# DEPS:    stdlib only
# ==============================================================================

from __future__ import annotations


#: Mapping from research session exception message snippets to safe
#: (status_code, user_message) tuples used by the CLI.
RESEARCH_SESSION_ERROR_CODES: dict[str, tuple[str, str]] = {
    "artifact_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "artifact_path_not_allowed": ("research_error", "Research command failed."),
    "artifact_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "ambiguous_run_id": ("invalid_research_id", "Invalid research identifier."),
    "ambiguous_research_id": ("invalid_research_id", "Invalid research identifier."),
    "ambiguous_plan_id": ("invalid_research_id", "Invalid research identifier."),
    "ambiguous_prompt_packet_id": ("invalid_research_id", "Invalid research identifier."),
    "plan_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "prompt_packet_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "prompt_packet_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "provider_response_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_response_malformed": ("provider_response_malformed", "Provider response is malformed."),
    "ambiguous_provider_response_id": ("invalid_research_id", "Invalid research identifier."),
    "evaluation_data_invalid": ("evaluation_data_invalid", "Evaluation data is invalid."),
    "limit_must_be_positive": ("research_error", "Research command failed."),
    "run_id must not be empty": ("invalid_research_id", "Invalid research identifier."),
    "run_id contains unsafe characters": ("invalid_research_id", "Invalid research identifier."),
    "run_id exceeds maximum length": ("invalid_research_id", "Invalid research identifier."),
    "invalid_max_context_chars": ("invalid_max_context_chars", "Invalid max-context-chars value."),
    "max_context_chars_exceeds_limit": ("invalid_max_context_chars", "Invalid max-context-chars value."),
    "invalid_research_identifier": ("invalid_research_id", "Invalid research identifier."),
    "invalid_research_symbol": ("invalid_research_symbol", "Invalid research symbol."),
    "invalid_source_run_id": ("invalid_source_run_id", "Invalid sandbox lineage."),
    "invalid_prompt_packet_id": ("invalid_prompt_packet_id", "Invalid sandbox lineage."),
    "invalid_sandbox_lineage": ("invalid_sandbox_lineage", "Invalid sandbox lineage."),
    "sandbox_request_not_found": ("sandbox_request_not_found", "Sandbox request not found."),
    "sandbox_request_malformed": ("sandbox_request_malformed", "Sandbox request is malformed."),
    "unsupported_sandbox_schema": ("unsupported_sandbox_schema", "Unsupported sandbox schema."),
    "ambiguous_sandbox_request_id": ("invalid_sandbox_request_id", "Invalid sandbox request ID."),
    "sandbox_replay_mismatch": ("sandbox_replay_mismatch", "Sandbox replay mismatch."),
    "provider_response_file_not_found": ("provider_response_file_not_found", "Provider response file not found."),
    "provider_response_unsafe": ("provider_response_unsafe", "Provider response is unsafe."),
    "provider_response_import_failed": ("provider_response_import_failed", "Provider response import failed."),
    "invalid_provider_id": ("invalid_provider_id", "Invalid provider ID."),
    "invalid_model_id": ("invalid_model_id", "Invalid model ID."),
    "provider_call_plan_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_call_plan_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "ambiguous_provider_call_plan_id": ("invalid_research_id", "Invalid research identifier."),
    "unsupported_provider_call_plan_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "invalid_provider_call_plan_lineage": ("invalid_provider_call_plan_lineage", "Invalid provider call-plan artifact."),
    "invalid_provider_call_plan_provider": ("invalid_provider_call_plan_provider", "Invalid provider call-plan artifact."),
    "invalid_provider_call_plan_model": ("invalid_provider_call_plan_model", "Invalid provider call-plan artifact."),
    "provider_call_plan_hash_mismatch": ("provider_call_plan_hash_mismatch", "Invalid provider call-plan artifact."),
    "provider_call_plan_source_missing": ("provider_call_plan_source_missing", "Invalid provider call-plan artifact."),
    "provider_call_plan_source_hash_mismatch": ("provider_call_plan_source_hash_mismatch", "Invalid provider call-plan artifact."),
    "provider_execution_dry_run_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_execution_dry_run_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "ambiguous_provider_execution_dry_run_id": ("invalid_research_id", "Invalid research identifier."),
    "unsupported_provider_execution_dry_run_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "invalid_provider_execution_dry_run_lineage": ("invalid_provider_execution_dry_run_lineage", "Invalid provider execution dry-run artifact."),
    "invalid_provider_execution_dry_run_provider": ("invalid_provider_execution_dry_run_provider", "Invalid provider execution dry-run artifact."),
    "invalid_provider_execution_dry_run_model": ("invalid_provider_execution_dry_run_model", "Invalid provider execution dry-run artifact."),
    "provider_execution_dry_run_hash_mismatch": ("provider_execution_dry_run_hash_mismatch", "Invalid provider execution dry-run artifact."),
    "provider_execution_dry_run_source_missing": ("provider_execution_dry_run_source_missing", "Invalid provider execution dry-run artifact."),
    "provider_execution_dry_run_source_hash_mismatch": ("provider_execution_dry_run_source_hash_mismatch", "Invalid provider execution dry-run artifact."),
    "provider_execution_dry_run_impossible_boolean": ("provider_execution_dry_run_impossible_boolean", "Invalid provider execution dry-run artifact."),
    "invalid_provider_execution_state_name": ("invalid_provider_execution_state_name", "Invalid provider execution state."),
    "provider_execution_state_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_execution_state_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "ambiguous_provider_execution_state_id": ("invalid_research_id", "Invalid research identifier."),
    "unsupported_provider_execution_state_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "invalid_provider_execution_state_lineage": ("invalid_provider_execution_state_lineage", "Invalid provider execution state artifact."),
    "invalid_provider_execution_state_provider": ("invalid_provider_execution_state_provider", "Invalid provider execution state artifact."),
    "invalid_provider_execution_state_model": ("invalid_provider_execution_state_model", "Invalid provider execution state artifact."),
    "provider_execution_state_hash_mismatch": ("provider_execution_state_hash_mismatch", "Invalid provider execution state artifact."),
    "provider_execution_state_source_dry_run_missing": ("provider_execution_state_source_dry_run_missing", "Invalid provider execution state artifact."),
    "provider_execution_state_source_dry_run_hash_mismatch": ("provider_execution_state_source_dry_run_hash_mismatch", "Invalid provider execution state artifact."),
    "provider_execution_state_impossible_boolean": ("provider_execution_state_impossible_boolean", "Invalid provider execution state artifact."),
    "invalid_provider_execution_audit_packet_status": ("invalid_provider_execution_audit_packet_status", "Invalid provider execution audit packet."),
    "invalid_provider_execution_audit_packet_lineage": ("invalid_provider_execution_audit_packet_lineage", "Invalid provider execution audit packet artifact."),
    "invalid_provider_execution_audit_packet_provider": ("invalid_provider_execution_audit_packet_provider", "Invalid provider execution audit packet artifact."),
    "invalid_provider_execution_audit_packet_model": ("invalid_provider_execution_audit_packet_model", "Invalid provider execution audit packet artifact."),
    "provider_execution_audit_packet_hash_mismatch": ("provider_execution_audit_packet_hash_mismatch", "Invalid provider execution audit packet artifact."),
    "provider_execution_audit_packet_source_state_missing": ("provider_execution_audit_packet_source_state_missing", "Invalid provider execution audit packet artifact."),
    "provider_execution_audit_packet_source_state_hash_mismatch": ("provider_execution_audit_packet_source_state_hash_mismatch", "Invalid provider execution audit packet artifact."),
    "provider_execution_audit_packet_impossible_boolean": ("provider_execution_audit_packet_impossible_boolean", "Invalid provider execution audit packet artifact."),
    "provider_execution_audit_packet_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_execution_audit_packet_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "ambiguous_provider_execution_audit_packet_id": ("invalid_research_id", "Invalid research identifier."),
    "unsupported_provider_execution_audit_packet_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "invalid_provider_execution_readiness_report_status": ("invalid_provider_execution_readiness_report_status", "Invalid provider execution readiness report."),
    "invalid_provider_execution_readiness_report_lineage": ("invalid_provider_execution_readiness_report_lineage", "Invalid provider execution readiness report artifact."),
    "invalid_provider_execution_readiness_report_provider": ("invalid_provider_execution_readiness_report_provider", "Invalid provider execution readiness report artifact."),
    "invalid_provider_execution_readiness_report_model": ("invalid_provider_execution_readiness_report_model", "Invalid provider execution readiness report artifact."),
    "provider_execution_readiness_report_hash_mismatch": ("provider_execution_readiness_report_hash_mismatch", "Invalid provider execution readiness report artifact."),
    "provider_execution_readiness_report_source_audit_packet_missing": ("provider_execution_readiness_report_source_audit_packet_missing", "Invalid provider execution readiness report artifact."),
    "provider_execution_readiness_report_source_audit_packet_hash_mismatch": ("provider_execution_readiness_report_source_audit_packet_hash_mismatch", "Invalid provider execution readiness report artifact."),
    "provider_execution_readiness_report_impossible_boolean": ("provider_execution_readiness_report_impossible_boolean", "Invalid provider execution readiness report artifact."),
    "provider_execution_readiness_report_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_execution_readiness_report_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "ambiguous_provider_execution_readiness_report_id": ("invalid_research_id", "Invalid research identifier."),
    "unsupported_provider_execution_readiness_report_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "invalid_provider_preflight_freeze_id": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_preflight_freeze_lineage": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_preflight_freeze_status": ("invalid_provider_preflight_freeze_status", "Invalid provider preflight freeze artifact."),
    "invalid_provider_preflight_freeze_model": ("invalid_provider_preflight_freeze_model", "Invalid provider preflight freeze artifact."),
    "invalid_provider_preflight_freeze_provider": ("invalid_provider_preflight_freeze_provider", "Invalid provider preflight freeze artifact."),
    "provider_preflight_freeze_hash_mismatch": ("provider_preflight_freeze_hash_mismatch", "Invalid provider preflight freeze artifact."),
    "provider_preflight_freeze_source_readiness_missing": ("provider_preflight_freeze_source_readiness_missing", "Invalid provider preflight freeze artifact."),
    "provider_preflight_freeze_source_readiness_hash_mismatch": ("provider_preflight_freeze_source_readiness_hash_mismatch", "Invalid provider preflight freeze artifact."),
    "provider_preflight_freeze_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "unsupported_provider_preflight_freeze_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "provider_preflight_freeze_impossible_boolean": ("provider_preflight_freeze_impossible_boolean", "Invalid provider preflight freeze artifact."),
    "provider_preflight_freeze_impossible_attestation": ("provider_preflight_freeze_impossible_boolean", "Invalid provider preflight freeze artifact."),
    "provider_preflight_freeze_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "ambiguous_provider_preflight_freeze_id": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_opt_in_policy_id": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_opt_in_policy_lineage": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_opt_in_policy_status": ("invalid_provider_opt_in_policy_status", "Invalid provider opt-in policy artifact."),
    "invalid_provider_opt_in_policy_model": ("invalid_provider_opt_in_policy_model", "Invalid provider opt-in policy artifact."),
    "invalid_provider_opt_in_policy_provider": ("invalid_provider_opt_in_policy_provider", "Invalid provider opt-in policy artifact."),
    "provider_opt_in_policy_hash_mismatch": ("provider_opt_in_policy_hash_mismatch", "Invalid provider opt-in policy artifact."),
    "provider_opt_in_policy_source_freeze_missing": ("provider_opt_in_policy_source_freeze_missing", "Invalid provider opt-in policy artifact."),
    "provider_opt_in_policy_source_freeze_hash_mismatch": ("provider_opt_in_policy_source_freeze_hash_mismatch", "Invalid provider opt-in policy artifact."),
    "provider_opt_in_policy_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "unsupported_provider_opt_in_policy_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "provider_opt_in_policy_impossible_boolean": ("provider_opt_in_policy_impossible_boolean", "Invalid provider opt-in policy artifact."),
    "provider_opt_in_policy_forbidden_claim": ("provider_opt_in_policy_forbidden_claim", "Invalid provider opt-in policy artifact."),
    "provider_opt_in_policy_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "ambiguous_provider_opt_in_policy_id": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_response_intake_policy_provider": ("invalid_provider_response_intake_policy_provider", "Invalid provider response intake policy artifact."),
    "invalid_provider_response_intake_policy_model": ("invalid_provider_response_intake_policy_model", "Invalid provider response intake policy artifact."),
    "invalid_provider_response_intake_policy_status": ("invalid_provider_response_intake_policy_status", "Invalid provider response intake policy artifact."),
    "provider_response_intake_policy_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "unsupported_provider_response_intake_policy_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "provider_response_intake_policy_hash_mismatch": ("provider_response_intake_policy_hash_mismatch", "Invalid provider response intake policy artifact."),
    "provider_response_intake_policy_source_payload_preview_missing": ("provider_response_intake_policy_source_payload_preview_missing", "Invalid provider response intake policy artifact."),
    "provider_response_intake_policy_source_payload_preview_hash_mismatch": ("provider_response_intake_policy_source_payload_preview_hash_mismatch", "Invalid provider response intake policy artifact."),
    "invalid_provider_response_intake_policy_lineage": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_response_intake_policy_artifact": ("research_artifact_malformed", "Research artifact is malformed."),
    "provider_response_intake_policy_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_response_intake_policy_impossible_boolean": ("provider_response_intake_policy_impossible_boolean", "Invalid provider response intake policy artifact."),
    "provider_response_intake_policy_forbidden_response_claim": ("provider_response_intake_policy_forbidden_response_claim", "Invalid provider response intake policy artifact."),
    "invalid_provider_request_response_pairing_provider": ("invalid_provider_request_response_pairing_provider", "Invalid provider request/response pairing artifact."),
    "invalid_provider_request_response_pairing_model": ("invalid_provider_request_response_pairing_model", "Invalid provider request/response pairing artifact."),
    "invalid_provider_request_response_pairing_status": ("invalid_provider_request_response_pairing_status", "Invalid provider request/response pairing artifact."),
    "provider_request_response_pairing_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "unsupported_provider_request_response_pairing_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "provider_request_response_pairing_hash_mismatch": ("provider_request_response_pairing_hash_mismatch", "Invalid provider request/response pairing artifact."),
    "provider_request_response_pairing_source_response_intake_missing": ("provider_request_response_pairing_source_response_intake_missing", "Invalid provider request/response pairing artifact."),
    "provider_request_response_pairing_source_response_intake_hash_mismatch": ("provider_request_response_pairing_source_response_intake_hash_mismatch", "Invalid provider request/response pairing artifact."),
    "provider_request_response_pairing_source_payload_preview_missing": ("provider_request_response_pairing_source_payload_preview_missing", "Invalid provider request/response pairing artifact."),
    "provider_request_response_pairing_source_payload_preview_hash_mismatch": ("provider_request_response_pairing_source_payload_preview_hash_mismatch", "Invalid provider request/response pairing artifact."),
    "invalid_provider_request_response_pairing_lineage": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_request_response_pairing_artifact": ("research_artifact_malformed", "Research artifact is malformed."),
    "provider_request_response_pairing_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_request_response_pairing_impossible_boolean": ("provider_request_response_pairing_impossible_boolean", "Invalid provider request/response pairing artifact."),
    "provider_request_response_pairing_forbidden_pairing_claim": ("provider_request_response_pairing_forbidden_pairing_claim", "Invalid provider request/response pairing artifact."),
}


def safe_research_session_error(exc: Exception) -> tuple[str, str]:
    """Map a research session exception to a safe static status and message."""
    code = str(exc)
    return RESEARCH_SESSION_ERROR_CODES.get(code, ("research_error", "Research command failed."))
