# ==============================================================================
# PROJECT: Atlas Agent
# FILE:    research/errors.py
# PURPOSE: The error types of the research domain, and their sanitised messages.
# DEPS:    stdlib only
# ==============================================================================

from __future__ import annotations


#: Mapping from research session exception message snippets to safe
#: (status_code, user_message) tuples used by the CLI.
RESEARCH_SESSION_ERROR_CODES: dict[str, tuple[str, str]] = {
    "artifact_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "artifact_path_not_allowed": ("research_error", "Research command failed."),
    "artifact_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "ambiguous_run_id": ("invalid_research_id", "Invalid research identifier."),
    "ambiguous_research_id": ("invalid_research_id", "Invalid research identifier."),
    "ambiguous_plan_id": ("invalid_research_id", "Invalid research identifier."),
    "ambiguous_prompt_packet_id": ("invalid_research_id", "Invalid research identifier."),
    "plan_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "prompt_packet_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "prompt_packet_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "provider_response_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_response_malformed": ("provider_response_malformed", "Provider response is malformed."),
    "ambiguous_provider_response_id": ("invalid_research_id", "Invalid research identifier."),
    "evaluation_data_invalid": ("evaluation_data_invalid", "Evaluation data is invalid."),
    "limit_must_be_positive": ("research_error", "Research command failed."),
    "run_id must not be empty": ("invalid_research_id", "Invalid research identifier."),
    "run_id contains unsafe characters": ("invalid_research_id", "Invalid research identifier."),
    "run_id exceeds maximum length": ("invalid_research_id", "Invalid research identifier."),
    "invalid_max_context_chars": ("invalid_max_context_chars", "Invalid max-context-chars value."),
    "max_context_chars_exceeds_limit": ("invalid_max_context_chars", "Invalid max-context-chars value."),
    "invalid_research_identifier": ("invalid_research_id", "Invalid research identifier."),
    "invalid_research_symbol": ("invalid_research_symbol", "Invalid research symbol."),
    "invalid_source_run_id": ("invalid_source_run_id", "Invalid sandbox lineage."),
    "invalid_prompt_packet_id": ("invalid_prompt_packet_id", "Invalid sandbox lineage."),
    "invalid_sandbox_lineage": ("invalid_sandbox_lineage", "Invalid sandbox lineage."),
    "sandbox_request_not_found": ("sandbox_request_not_found", "Sandbox request not found."),
    "sandbox_request_malformed": ("sandbox_request_malformed", "Sandbox request is malformed."),
    "unsupported_sandbox_schema": ("unsupported_sandbox_schema", "Unsupported sandbox schema."),
    "ambiguous_sandbox_request_id": ("invalid_sandbox_request_id", "Invalid sandbox request ID."),
    "sandbox_replay_mismatch": ("sandbox_replay_mismatch", "Sandbox replay mismatch."),
    "provider_response_file_not_found": ("provider_response_file_not_found", "Provider response file not found."),
    "provider_response_unsafe": ("provider_response_unsafe", "Provider response is unsafe."),
    "provider_response_import_failed": ("provider_response_import_failed", "Provider response import failed."),
    "invalid_provider_id": ("invalid_provider_id", "Invalid provider ID."),
    "invalid_model_id": ("invalid_model_id", "Invalid model ID."),
    "provider_call_plan_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_call_plan_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "ambiguous_provider_call_plan_id": ("invalid_research_id", "Invalid research identifier."),
    "unsupported_provider_call_plan_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "invalid_provider_call_plan_lineage": ("invalid_provider_call_plan_lineage", "Invalid provider call-plan artifact."),
    "invalid_provider_call_plan_provider": ("invalid_provider_call_plan_provider", "Invalid provider call-plan artifact."),
    "invalid_provider_call_plan_model": ("invalid_provider_call_plan_model", "Invalid provider call-plan artifact."),
    "provider_call_plan_hash_mismatch": ("provider_call_plan_hash_mismatch", "Invalid provider call-plan artifact."),
    "provider_call_plan_source_missing": ("provider_call_plan_source_missing", "Invalid provider call-plan artifact."),
    "provider_call_plan_source_hash_mismatch": ("provider_call_plan_source_hash_mismatch", "Invalid provider call-plan artifact."),
    "provider_execution_dry_run_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_execution_dry_run_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "ambiguous_provider_execution_dry_run_id": ("invalid_research_id", "Invalid research identifier."),
    "unsupported_provider_execution_dry_run_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "invalid_provider_execution_dry_run_lineage": ("invalid_provider_execution_dry_run_lineage", "Invalid provider execution dry-run artifact."),
    "invalid_provider_execution_dry_run_provider": ("invalid_provider_execution_dry_run_provider", "Invalid provider execution dry-run artifact."),
    "invalid_provider_execution_dry_run_model": ("invalid_provider_execution_dry_run_model", "Invalid provider execution dry-run artifact."),
    "provider_execution_dry_run_hash_mismatch": ("provider_execution_dry_run_hash_mismatch", "Invalid provider execution dry-run artifact."),
    "provider_execution_dry_run_source_missing": ("provider_execution_dry_run_source_missing", "Invalid provider execution dry-run artifact."),
    "provider_execution_dry_run_source_hash_mismatch": ("provider_execution_dry_run_source_hash_mismatch", "Invalid provider execution dry-run artifact."),
    "provider_execution_dry_run_impossible_boolean": ("provider_execution_dry_run_impossible_boolean", "Invalid provider execution dry-run artifact."),
    "invalid_provider_execution_state_name": ("invalid_provider_execution_state_name", "Invalid provider execution state."),
    "provider_execution_state_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_execution_state_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "ambiguous_provider_execution_state_id": ("invalid_research_id", "Invalid research identifier."),
    "unsupported_provider_execution_state_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "invalid_provider_execution_state_lineage": ("invalid_provider_execution_state_lineage", "Invalid provider execution state artifact."),
    "invalid_provider_execution_state_provider": ("invalid_provider_execution_state_provider", "Invalid provider execution state artifact."),
    "invalid_provider_execution_state_model": ("invalid_provider_execution_state_model", "Invalid provider execution state artifact."),
    "provider_execution_state_hash_mismatch": ("provider_execution_state_hash_mismatch", "Invalid provider execution state artifact."),
    "provider_execution_state_source_dry_run_missing": ("provider_execution_state_source_dry_run_missing", "Invalid provider execution state artifact."),
    "provider_execution_state_source_dry_run_hash_mismatch": ("provider_execution_state_source_dry_run_hash_mismatch", "Invalid provider execution state artifact."),
    "provider_execution_state_impossible_boolean": ("provider_execution_state_impossible_boolean", "Invalid provider execution state artifact."),
    "invalid_provider_execution_audit_packet_status": ("invalid_provider_execution_audit_packet_status", "Invalid provider execution audit packet."),
    "invalid_provider_execution_audit_packet_lineage": ("invalid_provider_execution_audit_packet_lineage", "Invalid provider execution audit packet artifact."),
    "invalid_provider_execution_audit_packet_provider": ("invalid_provider_execution_audit_packet_provider", "Invalid provider execution audit packet artifact."),
    "invalid_provider_execution_audit_packet_model": ("invalid_provider_execution_audit_packet_model", "Invalid provider execution audit packet artifact."),
    "provider_execution_audit_packet_hash_mismatch": ("provider_execution_audit_packet_hash_mismatch", "Invalid provider execution audit packet artifact."),
    "provider_execution_audit_packet_source_state_missing": ("provider_execution_audit_packet_source_state_missing", "Invalid provider execution audit packet artifact."),
    "provider_execution_audit_packet_source_state_hash_mismatch": ("provider_execution_audit_packet_source_state_hash_mismatch", "Invalid provider execution audit packet artifact."),
    "provider_execution_audit_packet_impossible_boolean": ("provider_execution_audit_packet_impossible_boolean", "Invalid provider execution audit packet artifact."),
    "provider_execution_audit_packet_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_execution_audit_packet_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "ambiguous_provider_execution_audit_packet_id": ("invalid_research_id", "Invalid research identifier."),
    "unsupported_provider_execution_audit_packet_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "invalid_provider_execution_readiness_report_status": ("invalid_provider_execution_readiness_report_status", "Invalid provider execution readiness report."),
    "invalid_provider_execution_readiness_report_lineage": ("invalid_provider_execution_readiness_report_lineage", "Invalid provider execution readiness report artifact."),
    "invalid_provider_execution_readiness_report_provider": ("invalid_provider_execution_readiness_report_provider", "Invalid provider execution readiness report artifact."),
    "invalid_provider_execution_readiness_report_model": ("invalid_provider_execution_readiness_report_model", "Invalid provider execution readiness report artifact."),
    "provider_execution_readiness_report_hash_mismatch": ("provider_execution_readiness_report_hash_mismatch", "Invalid provider execution readiness report artifact."),
    "provider_execution_readiness_report_source_audit_packet_missing": ("provider_execution_readiness_report_source_audit_packet_missing", "Invalid provider execution readiness report artifact."),
    "provider_execution_readiness_report_source_audit_packet_hash_mismatch": ("provider_execution_readiness_report_source_audit_packet_hash_mismatch", "Invalid provider execution readiness report artifact."),
    "provider_execution_readiness_report_impossible_boolean": ("provider_execution_readiness_report_impossible_boolean", "Invalid provider execution readiness report artifact."),
    "provider_execution_readiness_report_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_execution_readiness_report_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "ambiguous_provider_execution_readiness_report_id": ("invalid_research_id", "Invalid research identifier."),
    "unsupported_provider_execution_readiness_report_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "invalid_provider_preflight_freeze_id": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_preflight_freeze_lineage": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_preflight_freeze_status": ("invalid_provider_preflight_freeze_status", "Invalid provider preflight freeze artifact."),
    "invalid_provider_preflight_freeze_model": ("invalid_provider_preflight_freeze_model", "Invalid provider preflight freeze artifact."),
    "invalid_provider_preflight_freeze_provider": ("invalid_provider_preflight_freeze_provider", "Invalid provider preflight freeze artifact."),
    "provider_preflight_freeze_hash_mismatch": ("provider_preflight_freeze_hash_mismatch", "Invalid provider preflight freeze artifact."),
    "provider_preflight_freeze_source_readiness_missing": ("provider_preflight_freeze_source_readiness_missing", "Invalid provider preflight freeze artifact."),
    "provider_preflight_freeze_source_readiness_hash_mismatch": ("provider_preflight_freeze_source_readiness_hash_mismatch", "Invalid provider preflight freeze artifact."),
    "provider_preflight_freeze_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "unsupported_provider_preflight_freeze_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "provider_preflight_freeze_impossible_boolean": ("provider_preflight_freeze_impossible_boolean", "Invalid provider preflight freeze artifact."),
    "provider_preflight_freeze_impossible_attestation": ("provider_preflight_freeze_impossible_boolean", "Invalid provider preflight freeze artifact."),
    "provider_preflight_freeze_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "ambiguous_provider_preflight_freeze_id": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_opt_in_policy_id": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_opt_in_policy_lineage": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_opt_in_policy_status": ("invalid_provider_opt_in_policy_status", "Invalid provider opt-in policy artifact."),
    "invalid_provider_opt_in_policy_model": ("invalid_provider_opt_in_policy_model", "Invalid provider opt-in policy artifact."),
    "invalid_provider_opt_in_policy_provider": ("invalid_provider_opt_in_policy_provider", "Invalid provider opt-in policy artifact."),
    "provider_opt_in_policy_hash_mismatch": ("provider_opt_in_policy_hash_mismatch", "Invalid provider opt-in policy artifact."),
    "provider_opt_in_policy_source_freeze_missing": ("provider_opt_in_policy_source_freeze_missing", "Invalid provider opt-in policy artifact."),
    "provider_opt_in_policy_source_freeze_hash_mismatch": ("provider_opt_in_policy_source_freeze_hash_mismatch", "Invalid provider opt-in policy artifact."),
    "provider_opt_in_policy_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "unsupported_provider_opt_in_policy_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "provider_opt_in_policy_impossible_boolean": ("provider_opt_in_policy_impossible_boolean", "Invalid provider opt-in policy artifact."),
    "provider_opt_in_policy_forbidden_claim": ("provider_opt_in_policy_forbidden_claim", "Invalid provider opt-in policy artifact."),
    "provider_opt_in_policy_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "ambiguous_provider_opt_in_policy_id": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_response_intake_policy_provider": ("invalid_provider_response_intake_policy_provider", "Invalid provider response intake policy artifact."),
    "invalid_provider_response_intake_policy_model": ("invalid_provider_response_intake_policy_model", "Invalid provider response intake policy artifact."),
    "invalid_provider_response_intake_policy_status": ("invalid_provider_response_intake_policy_status", "Invalid provider response intake policy artifact."),
    "provider_response_intake_policy_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "unsupported_provider_response_intake_policy_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "provider_response_intake_policy_hash_mismatch": ("provider_response_intake_policy_hash_mismatch", "Invalid provider response intake policy artifact."),
    "provider_response_intake_policy_source_payload_preview_missing": ("provider_response_intake_policy_source_payload_preview_missing", "Invalid provider response intake policy artifact."),
    "provider_response_intake_policy_source_payload_preview_hash_mismatch": ("provider_response_intake_policy_source_payload_preview_hash_mismatch", "Invalid provider response intake policy artifact."),
    "invalid_provider_response_intake_policy_lineage": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_response_intake_policy_artifact": ("research_artifact_malformed", "Research artifact is malformed."),
    "provider_response_intake_policy_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_response_intake_policy_impossible_boolean": ("provider_response_intake_policy_impossible_boolean", "Invalid provider response intake policy artifact."),
    "provider_response_intake_policy_forbidden_response_claim": ("provider_response_intake_policy_forbidden_response_claim", "Invalid provider response intake policy artifact."),
    "invalid_provider_request_response_pairing_provider": ("invalid_provider_request_response_pairing_provider", "Invalid provider request/response pairing artifact."),
    "invalid_provider_request_response_pairing_model": ("invalid_provider_request_response_pairing_model", "Invalid provider request/response pairing artifact."),
    "invalid_provider_request_response_pairing_status": ("invalid_provider_request_response_pairing_status", "Invalid provider request/response pairing artifact."),
    "provider_request_response_pairing_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "unsupported_provider_request_response_pairing_schema": ("unsupported_research_artifact_schema", "Unsupported research artifact schema."),
    "provider_request_response_pairing_hash_mismatch": ("provider_request_response_pairing_hash_mismatch", "Invalid provider request/response pairing artifact."),
    "provider_request_response_pairing_source_response_intake_missing": ("provider_request_response_pairing_source_response_intake_missing", "Invalid provider request/response pairing artifact."),
    "provider_request_response_pairing_source_response_intake_hash_mismatch": ("provider_request_response_pairing_source_response_intake_hash_mismatch", "Invalid provider request/response pairing artifact."),
    "provider_request_response_pairing_source_payload_preview_missing": ("provider_request_response_pairing_source_payload_preview_missing", "Invalid provider request/response pairing artifact."),
    "provider_request_response_pairing_source_payload_preview_hash_mismatch": ("provider_request_response_pairing_source_payload_preview_hash_mismatch", "Invalid provider request/response pairing artifact."),
    "invalid_provider_request_response_pairing_lineage": ("invalid_research_id", "Invalid research identifier."),
    "invalid_provider_request_response_pairing_artifact": ("research_artifact_malformed", "Research artifact is malformed."),
    "provider_request_response_pairing_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_request_response_pairing_impossible_boolean": ("provider_request_response_pairing_impossible_boolean", "Invalid provider request/response pairing artifact."),
    "provider_request_response_pairing_forbidden_pairing_claim": ("provider_request_response_pairing_forbidden_pairing_claim", "Invalid provider request/response pairing artifact."),

    # --- CAND-034 -------------------------------------------------------------
    # The 136 codes that reached the operator as "Research command failed." while
    # the reason was known, static, and safe to show.
    #
    # The wording is not invented here. `preflight_freeze`, `opt_in_policy` and
    # `call_plan` were mapped independently and converged on the same five slots:
    # four shared messages -- identifier, malformed, unsupported schema, not
    # found -- plus one sentence naming the artifact, which carries most of a
    # family's codes. These entries follow that, so 136 codes needed 13 new
    # sentences rather than 136.
    #
    # The status stays per-code where the message is shared across a family: the
    # status is the machine-readable detail a client switches on, the message is
    # what a human reads, and the two are deliberately not the same granularity.
    #
    # These are literals, matched exactly. Nothing is derived from the code at
    # runtime -- 33 raise sites build their code with an f-string, and a pattern
    # rule would echo whatever string arrived. Those still land on the generic
    # fallback, which is the fail-safe half of this design and stays.
    "ambiguous_provider_credential_boundary_id": ("invalid_research_id", "Invalid research identifier."),
    "invalid_contract_symbol": ("invalid_research_symbol", "Invalid research symbol."),
    "invalid_provider_adapter_interface_contract_artifact": ("invalid_provider_adapter_interface_contract_artifact", "Invalid provider adapter interface contract artifact."),
    "invalid_provider_adapter_interface_contract_model": ("invalid_provider_adapter_interface_contract_model", "Invalid provider adapter interface contract artifact."),
    "invalid_provider_adapter_interface_contract_provider": ("invalid_provider_adapter_interface_contract_provider", "Invalid provider adapter interface contract artifact."),
    "invalid_provider_adapter_interface_contract_status": ("invalid_provider_adapter_interface_contract_status", "Invalid provider adapter interface contract artifact."),
    "invalid_provider_credential_boundary_status": ("invalid_provider_credential_boundary_status", "Invalid provider credential boundary artifact."),
    "invalid_provider_execution_unlock_state_artifact": ("invalid_provider_execution_unlock_state_artifact", "Invalid provider execution unlock state artifact."),
    "invalid_provider_execution_unlock_state_model": ("invalid_provider_execution_unlock_state_model", "Invalid provider execution unlock state artifact."),
    "invalid_provider_execution_unlock_state_provider": ("invalid_provider_execution_unlock_state_provider", "Invalid provider execution unlock state artifact."),
    "invalid_provider_execution_unlock_state_status": ("invalid_provider_execution_unlock_state_status", "Invalid provider execution unlock state artifact."),
    "invalid_provider_mock_response_final_safety_seal_model": ("invalid_provider_mock_response_final_safety_seal_model", "Invalid provider mock-response final safety seal artifact."),
    "invalid_provider_mock_response_final_safety_seal_provider": ("invalid_provider_mock_response_final_safety_seal_provider", "Invalid provider mock-response final safety seal artifact."),
    "invalid_provider_mock_response_final_safety_seal_status": ("invalid_provider_mock_response_final_safety_seal_status", "Invalid provider mock-response final safety seal artifact."),
    "invalid_provider_mock_response_import_candidate_artifact": ("invalid_provider_mock_response_import_candidate_artifact", "Invalid provider mock-response import candidate artifact."),
    "invalid_provider_mock_response_import_candidate_model": ("invalid_provider_mock_response_import_candidate_model", "Invalid provider mock-response import candidate artifact."),
    "invalid_provider_mock_response_import_candidate_provider": ("invalid_provider_mock_response_import_candidate_provider", "Invalid provider mock-response import candidate artifact."),
    "invalid_provider_mock_response_import_candidate_status": ("invalid_provider_mock_response_import_candidate_status", "Invalid provider mock-response import candidate artifact."),
    "invalid_provider_mock_response_review_sandbox_artifact": ("invalid_provider_mock_response_review_sandbox_artifact", "Invalid provider mock-response review sandbox artifact."),
    "invalid_provider_mock_response_review_sandbox_model": ("invalid_provider_mock_response_review_sandbox_model", "Invalid provider mock-response review sandbox artifact."),
    "invalid_provider_mock_response_review_sandbox_provider": ("invalid_provider_mock_response_review_sandbox_provider", "Invalid provider mock-response review sandbox artifact."),
    "invalid_provider_mock_response_review_sandbox_status": ("invalid_provider_mock_response_review_sandbox_status", "Invalid provider mock-response review sandbox artifact."),
    "invalid_provider_mock_response_simulation_artifact": ("invalid_provider_mock_response_simulation_artifact", "Invalid provider mock-response simulation artifact."),
    "invalid_provider_mock_response_simulation_model": ("invalid_provider_mock_response_simulation_model", "Invalid provider mock-response simulation artifact."),
    "invalid_provider_mock_response_simulation_provider": ("invalid_provider_mock_response_simulation_provider", "Invalid provider mock-response simulation artifact."),
    "invalid_provider_mock_response_simulation_status": ("invalid_provider_mock_response_simulation_status", "Invalid provider mock-response simulation artifact."),
    "invalid_provider_mock_response_trust_decision_blocker_model": ("invalid_provider_mock_response_trust_decision_blocker_model", "Invalid provider mock-response trust decision blocker artifact."),
    "invalid_provider_mock_response_trust_decision_blocker_provider": ("invalid_provider_mock_response_trust_decision_blocker_provider", "Invalid provider mock-response trust decision blocker artifact."),
    "invalid_provider_mock_response_trust_decision_blocker_status": ("invalid_provider_mock_response_trust_decision_blocker_status", "Invalid provider mock-response trust decision blocker artifact."),
    "invalid_provider_outbound_payload_preview_artifact": ("invalid_provider_outbound_payload_preview_artifact", "Invalid provider outbound payload preview artifact."),
    "invalid_provider_outbound_payload_preview_model": ("invalid_provider_outbound_payload_preview_model", "Invalid provider outbound payload preview artifact."),
    "invalid_provider_outbound_payload_preview_provider": ("invalid_provider_outbound_payload_preview_provider", "Invalid provider outbound payload preview artifact."),
    "invalid_provider_outbound_payload_preview_status": ("invalid_provider_outbound_payload_preview_status", "Invalid provider outbound payload preview artifact."),
    "invalid_provider_response_review_result_artifact": ("invalid_provider_response_review_result_artifact", "Invalid provider response review result artifact."),
    "invalid_provider_response_review_result_model": ("invalid_provider_response_review_result_model", "Invalid provider response review result artifact."),
    "invalid_provider_response_review_result_provider": ("invalid_provider_response_review_result_provider", "Invalid provider response review result artifact."),
    "invalid_provider_response_review_result_status": ("invalid_provider_response_review_result_status", "Invalid provider response review result artifact."),
    "invalid_provider_response_schema_contract_artifact": ("invalid_provider_response_schema_contract_artifact", "Invalid provider response schema contract artifact."),
    "invalid_provider_response_schema_contract_model": ("invalid_provider_response_schema_contract_model", "Invalid provider response schema contract artifact."),
    "invalid_provider_response_schema_contract_provider": ("invalid_provider_response_schema_contract_provider", "Invalid provider response schema contract artifact."),
    "invalid_provider_response_schema_contract_status": ("invalid_provider_response_schema_contract_status", "Invalid provider response schema contract artifact."),
    "invalid_provider_safety_dossier_provider": ("invalid_provider_safety_dossier_provider", "Invalid provider safety dossier artifact."),
    "invalid_provider_safety_dossier_status_filter": ("invalid_provider_safety_dossier_status_filter", "Invalid provider safety dossier artifact."),
    "output_path_outside_workspace": ("research_error", "Research command failed."),
    "provider_adapter_interface_contract_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "provider_adapter_interface_contract_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_adapter_interface_contract_source_pairing_missing": ("provider_adapter_interface_contract_source_pairing_missing", "Invalid provider adapter interface contract artifact."),
    "provider_adapter_interface_contract_source_payload_preview_missing": ("provider_adapter_interface_contract_source_payload_preview_missing", "Invalid provider adapter interface contract artifact."),
    "provider_adapter_interface_contract_source_response_intake_missing": ("provider_adapter_interface_contract_source_response_intake_missing", "Invalid provider adapter interface contract artifact."),
    "provider_adapter_interface_contract_source_review_result_missing": ("provider_adapter_interface_contract_source_review_result_missing", "Invalid provider adapter interface contract artifact."),
    "provider_adapter_interface_contract_source_schema_contract_missing": ("provider_adapter_interface_contract_source_schema_contract_missing", "Invalid provider adapter interface contract artifact."),
    "provider_adapter_interface_contract_source_unlock_state_missing": ("provider_adapter_interface_contract_source_unlock_state_missing", "Invalid provider adapter interface contract artifact."),
    "provider_credential_boundary_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "provider_credential_boundary_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_execution_unlock_state_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "provider_execution_unlock_state_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_execution_unlock_state_source_pairing_missing": ("provider_execution_unlock_state_source_pairing_missing", "Invalid provider execution unlock state artifact."),
    "provider_execution_unlock_state_source_payload_preview_missing": ("provider_execution_unlock_state_source_payload_preview_missing", "Invalid provider execution unlock state artifact."),
    "provider_execution_unlock_state_source_response_intake_missing": ("provider_execution_unlock_state_source_response_intake_missing", "Invalid provider execution unlock state artifact."),
    "provider_execution_unlock_state_source_review_result_missing": ("provider_execution_unlock_state_source_review_result_missing", "Invalid provider execution unlock state artifact."),
    "provider_execution_unlock_state_source_schema_contract_missing": ("provider_execution_unlock_state_source_schema_contract_missing", "Invalid provider execution unlock state artifact."),
    "provider_mock_response_final_safety_seal_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_mock_response_final_safety_seal_source_trust_decision_blocker_missing": ("provider_mock_response_final_safety_seal_source_trust_decision_blocker_missing", "Invalid provider mock-response final safety seal artifact."),
    "provider_mock_response_final_safety_seal_source_trust_decision_blocker_provider_not_mock": ("provider_mock_response_final_safety_seal_source_trust_decision_blocker_provider_not_mock", "Invalid provider mock-response final safety seal artifact."),
    "provider_mock_response_import_candidate_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "provider_mock_response_import_candidate_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_mock_response_import_candidate_source_adapter_interface_missing": ("provider_mock_response_import_candidate_source_adapter_interface_missing", "Invalid provider mock-response import candidate artifact."),
    "provider_mock_response_import_candidate_source_mock_response_missing": ("provider_mock_response_import_candidate_source_mock_response_missing", "Invalid provider mock-response import candidate artifact."),
    "provider_mock_response_import_candidate_source_mock_response_provider_not_mock": ("provider_mock_response_import_candidate_source_mock_response_provider_not_mock", "Invalid provider mock-response import candidate artifact."),
    "provider_mock_response_import_candidate_source_pairing_missing": ("provider_mock_response_import_candidate_source_pairing_missing", "Invalid provider mock-response import candidate artifact."),
    "provider_mock_response_import_candidate_source_payload_preview_missing": ("provider_mock_response_import_candidate_source_payload_preview_missing", "Invalid provider mock-response import candidate artifact."),
    "provider_mock_response_import_candidate_source_response_intake_missing": ("provider_mock_response_import_candidate_source_response_intake_missing", "Invalid provider mock-response import candidate artifact."),
    "provider_mock_response_import_candidate_source_review_result_missing": ("provider_mock_response_import_candidate_source_review_result_missing", "Invalid provider mock-response import candidate artifact."),
    "provider_mock_response_import_candidate_source_schema_contract_missing": ("provider_mock_response_import_candidate_source_schema_contract_missing", "Invalid provider mock-response import candidate artifact."),
    "provider_mock_response_import_candidate_source_unlock_state_missing": ("provider_mock_response_import_candidate_source_unlock_state_missing", "Invalid provider mock-response import candidate artifact."),
    "provider_mock_response_review_sandbox_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "provider_mock_response_review_sandbox_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_mock_response_review_sandbox_source_adapter_interface_missing": ("provider_mock_response_review_sandbox_source_adapter_interface_missing", "Invalid provider mock-response review sandbox artifact."),
    "provider_mock_response_review_sandbox_source_import_candidate_missing": ("provider_mock_response_review_sandbox_source_import_candidate_missing", "Invalid provider mock-response review sandbox artifact."),
    "provider_mock_response_review_sandbox_source_import_candidate_provider_not_mock": ("provider_mock_response_review_sandbox_source_import_candidate_provider_not_mock", "Invalid provider mock-response review sandbox artifact."),
    "provider_mock_response_review_sandbox_source_mock_response_missing": ("provider_mock_response_review_sandbox_source_mock_response_missing", "Invalid provider mock-response review sandbox artifact."),
    "provider_mock_response_review_sandbox_source_pairing_missing": ("provider_mock_response_review_sandbox_source_pairing_missing", "Invalid provider mock-response review sandbox artifact."),
    "provider_mock_response_review_sandbox_source_payload_preview_missing": ("provider_mock_response_review_sandbox_source_payload_preview_missing", "Invalid provider mock-response review sandbox artifact."),
    "provider_mock_response_review_sandbox_source_response_intake_missing": ("provider_mock_response_review_sandbox_source_response_intake_missing", "Invalid provider mock-response review sandbox artifact."),
    "provider_mock_response_review_sandbox_source_review_result_missing": ("provider_mock_response_review_sandbox_source_review_result_missing", "Invalid provider mock-response review sandbox artifact."),
    "provider_mock_response_review_sandbox_source_schema_contract_missing": ("provider_mock_response_review_sandbox_source_schema_contract_missing", "Invalid provider mock-response review sandbox artifact."),
    "provider_mock_response_review_sandbox_source_unlock_state_missing": ("provider_mock_response_review_sandbox_source_unlock_state_missing", "Invalid provider mock-response review sandbox artifact."),
    "provider_mock_response_simulation_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "provider_mock_response_simulation_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_mock_response_simulation_source_adapter_interface_missing": ("provider_mock_response_simulation_source_adapter_interface_missing", "Invalid provider mock-response simulation artifact."),
    "provider_mock_response_simulation_source_pairing_missing": ("provider_mock_response_simulation_source_pairing_missing", "Invalid provider mock-response simulation artifact."),
    "provider_mock_response_simulation_source_payload_preview_missing": ("provider_mock_response_simulation_source_payload_preview_missing", "Invalid provider mock-response simulation artifact."),
    "provider_mock_response_simulation_source_response_intake_missing": ("provider_mock_response_simulation_source_response_intake_missing", "Invalid provider mock-response simulation artifact."),
    "provider_mock_response_simulation_source_review_result_missing": ("provider_mock_response_simulation_source_review_result_missing", "Invalid provider mock-response simulation artifact."),
    "provider_mock_response_simulation_source_schema_contract_missing": ("provider_mock_response_simulation_source_schema_contract_missing", "Invalid provider mock-response simulation artifact."),
    "provider_mock_response_simulation_source_unlock_state_missing": ("provider_mock_response_simulation_source_unlock_state_missing", "Invalid provider mock-response simulation artifact."),
    "provider_mock_response_trust_decision_blocker_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_mock_response_trust_decision_blocker_source_adapter_interface_missing": ("provider_mock_response_trust_decision_blocker_source_adapter_interface_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_audit_packet_missing": ("provider_mock_response_trust_decision_blocker_source_audit_packet_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_call_plan_missing": ("provider_mock_response_trust_decision_blocker_source_call_plan_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_dry_run_missing": ("provider_mock_response_trust_decision_blocker_source_dry_run_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_execution_state_missing": ("provider_mock_response_trust_decision_blocker_source_execution_state_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_import_candidate_missing": ("provider_mock_response_trust_decision_blocker_source_import_candidate_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_mock_response_missing": ("provider_mock_response_trust_decision_blocker_source_mock_response_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_opt_in_policy_missing": ("provider_mock_response_trust_decision_blocker_source_opt_in_policy_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_pairing_missing": ("provider_mock_response_trust_decision_blocker_source_pairing_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_payload_preview_missing": ("provider_mock_response_trust_decision_blocker_source_payload_preview_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_preflight_freeze_missing": ("provider_mock_response_trust_decision_blocker_source_preflight_freeze_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_readiness_report_missing": ("provider_mock_response_trust_decision_blocker_source_readiness_report_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_response_intake_missing": ("provider_mock_response_trust_decision_blocker_source_response_intake_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_review_result_missing": ("provider_mock_response_trust_decision_blocker_source_review_result_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_review_sandbox_missing": ("provider_mock_response_trust_decision_blocker_source_review_sandbox_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_review_sandbox_provider_not_mock": ("provider_mock_response_trust_decision_blocker_source_review_sandbox_provider_not_mock", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_schema_contract_missing": ("provider_mock_response_trust_decision_blocker_source_schema_contract_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_mock_response_trust_decision_blocker_source_unlock_state_missing": ("provider_mock_response_trust_decision_blocker_source_unlock_state_missing", "Invalid provider mock-response trust decision blocker artifact."),
    "provider_outbound_payload_preview_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "provider_outbound_payload_preview_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_outbound_payload_preview_source_boundary_missing": ("provider_outbound_payload_preview_source_boundary_missing", "Invalid provider outbound payload preview artifact."),
    "provider_response_review_result_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "provider_response_review_result_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_response_review_result_source_pairing_missing": ("provider_response_review_result_source_pairing_missing", "Invalid provider response review result artifact."),
    "provider_response_review_result_source_payload_preview_missing": ("provider_response_review_result_source_payload_preview_missing", "Invalid provider response review result artifact."),
    "provider_response_review_result_source_response_intake_missing": ("provider_response_review_result_source_response_intake_missing", "Invalid provider response review result artifact."),
    "provider_response_review_result_source_schema_contract_missing": ("provider_response_review_result_source_schema_contract_missing", "Invalid provider response review result artifact."),
    "provider_response_schema_contract_malformed": ("research_artifact_malformed", "Research artifact is malformed."),
    "provider_response_schema_contract_not_found": ("research_artifact_not_found", "Research artifact not found."),
    "provider_response_schema_contract_source_pairing_missing": ("provider_response_schema_contract_source_pairing_missing", "Invalid provider response schema contract artifact."),
    "provider_response_schema_contract_source_payload_preview_missing": ("provider_response_schema_contract_source_payload_preview_missing", "Invalid provider response schema contract artifact."),
    "provider_response_schema_contract_source_response_intake_missing": ("provider_response_schema_contract_source_response_intake_missing", "Invalid provider response schema contract artifact."),
    "provider_safety_dossier_export_chain_incomplete": ("provider_safety_dossier_export_chain_incomplete", "Invalid provider safety dossier artifact."),
    "provider_safety_dossier_export_forbidden_fragment": ("provider_safety_dossier_export_forbidden_fragment", "Invalid provider safety dossier artifact."),
    "provider_safety_dossier_export_unsafe_claim": ("provider_safety_dossier_export_unsafe_claim", "Invalid provider safety dossier artifact."),
    "provider_safety_dossier_export_validation_failed": ("provider_safety_dossier_export_validation_failed", "Invalid provider safety dossier artifact."),
    "provider_safety_dossier_missing": ("provider_safety_dossier_missing", "Invalid provider safety dossier artifact."),
    "provider_safety_dossier_source_seal_missing": ("provider_safety_dossier_source_seal_missing", "Invalid provider safety dossier artifact."),
    "release_candidate_readiness_report_missing": ("release_candidate_readiness_report_missing", "Invalid release candidate readiness artifact."),
}


def safe_research_session_error(exc: Exception) -> tuple[str, str]:
    """Map a research session exception to a safe static status and message."""
    code = str(exc)
    return RESEARCH_SESSION_ERROR_CODES.get(code, ("research_error", "Research command failed."))
